version: '3.4'

services:
  # Core Services
  yb.platform.microservice.todo:
    image: ${DOCKER_REGISTRY:-yb}/yb-platform-microservice-todo
    build:
      context: .
      dockerfile: src/YB.Todo/Dockerfile

  # MS SQL Server
  mssqldb:
    image: "mcr.microsoft.com/mssql/server"
    environment:
       SA_PASSWORD: "mssql-password12345"
       ACCEPT_EULA: "Y"
    ports:
      - 1439:1433
