version: '3.4'

services:
  # Core Services
  yb.platform.microservice.todo:
    image: ${DOCKER_REGISTRY:-yb}/yb-platform-microservice-todo
    build:
      context: .
      dockerfile: src/YB.Todo/Dockerfile

  client:
    restart: unless-stopped
    image: client:latest
    build:
      context: .
      dockerfile: ui/src/Dockerfile
    ports:
      - 3001:3000
    volumes:
      - ./client:/usr/src/app/ui
    links:
      - yb.platform.microservice.todo
    command: yarn start
    tty: true
    stdin_open: true

  # MS SQL Server
  mssqldb:
    image: "mcr.microsoft.com/mssql/server"
    environment:
       SA_PASSWORD: "mssql-password12345"
       ACCEPT_EULA: "Y"
    ports:
      - 1439:1433
